FROM agrigorev/zoomcamp-bees-wasps:v2 

EXPOSE 8001

# Set environment variables
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8


# Copy Pipfiles
COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock

# Install Pipenv and dependencies
RUN pip install pipenv \
    && pipenv install --deploy --system



# Copy the application files
# Add all necessary scripts
ADD question_5_6.py .
ADD question_4.py .
ADD question_3.py .
ADD question_2.py .

# Run the application
ENTRYPOINT ["uvicorn", "question_5_6:app", "--host=0.0.0.0", "--port=8001"]