# Use an official Python runtime as a parent image
FROM python:3.10

EXPOSE 8001

# Set environment variables
ENV FLASK_APP=app.py
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8



# Copy Pipfiles
COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock

# Install Pipenv and dependencies
RUN pip install pipenv \
    && pipenv install --deploy --system


# Create a directory to store model files inside the container
RUN mkdir -p /app/models
RUN mkdir -p /app/asset

# Set the working directory in the container
WORKDIR /app

# Copy all necessary scripts
COPY models/ /app/models
COPY asset/ /app/asset

# Copy the application files
# Add all necessary scripts
ADD main.py /app

# Run the application
ENTRYPOINT ["uvicorn", "main:app", "--host=0.0.0.0", "--port=8001"]